services:
  bot:
    build: ./bot
    container_name: bot
    restart: always
    depends_on:
      - db
      - server
    environment:
      SERVER_HOST: server
      SERVER_PORT: 8001
      TELEGRAM_BOT_TOKEN: 7550040035:AAHBVMk1bg01h7DpUbQw7kHqAkb_IQlez5o

  server:
    build: ./server
    container_name: server
    restart: always
    depends_on:
      - db
    ports:
      - "8001:8001"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: telegramshopbot
      DATABASE_PORT: 3306
      TELEGRAM_BOT_TOKEN: 7550040035:AAHBVMk1bg01h7DpUbQw7kHqAkb_IQlez5o

  web:
    build: ./web
    container_name: web
    restart: always
    depends_on:
      - db
      - server
    ports:
      - "8000:8000"
    environment:
      SERVER_HOST: server
      SERVER_PORT: 8001

  db:
    image: mysql:8.3
    container_name: mysql_server
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: telegramshopbot
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
