# Generated by Django 5.1.3 on 2024-11-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_message'),
        ('frontend', '0003_orderstatus_order_orderitem'),
    ]

    operations = [
    ]
