# Generated by Django 5.1.1 on 2024-11-12 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_merge_0003_message_0003_orderstatus_order_orderitem'),
        ('frontend', '0005_user_name'),
    ]

    operations = [
    ]
